### ISSUE TITLE
DB周り繋ぎ込み

### ISSUE THREAD

**Issue by Daisuke-993** [Daisuke-993/GRM_backend#4]
DB(mysql)のmigrateモジュール(goose)
ORMのgorm

**Comment by okurosawa** [comment]
mysqlコンテナとの接続は確認完了。

TODO: コンテナに環境変数セットしたけど `goose status` したときに使用されてなくて手動でexportしなおさないといけない状態だったので解決する。

**Comment by okurosawa** [comment]
Thx!
